## Entorno

In [2]:
from bs4 import BeautifulSoup
import requests
import pandas as pd 
import urllib.parse

## Solicitud HTTP

### Guardar sitio web en variable

In [3]:
website = 'https://www.laencontre.com.pe/alquiler/departamentos/lima/san-martin-porres'

### Solicitud GET

In [4]:
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'} # <-- Para evitar que te bloqueen
response = requests.get(website, headers=headers, timeout=(5, 15) )

### Código de Estado

In [5]:
print ("=== INTERPRETACION ===")
print ("403:rechazado" " | " "200:aprobado")
response.status_code

=== INTERPRETACION ===
403:rechazado | 200:aprobado

200

## Objeto Soup

In [6]:
soup = BeautifulSoup(response.content, 'html.parser')

In [7]:
soup

<!DOCTYPE html>
<!--[if gte IE 6]><html class="ie" lang="es_PE"><![endif]--><!--[if !IE]--><html lang="es_PE"><!--[endif]-->
<head>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/><meta content="text/html; charset=utf-8" http-equiv="Content-Type"/><meta content="es_PE" http-equiv="content-language"/><meta content="no-cache" http-equiv="Pragma"/><meta content="no-cache" http-equiv="Cache-Control"/>
<script type="text/javascript">(window.NREUM||(NREUM={})).init={privacy:{cookies_enabled:true},ajax:{deny_list:["bam.nr-data.net"]},distributed_tracing:{enabled:true}};(window.NREUM||(NREUM={})).loader_config={agentID:"1834328805",accountID:"3255554",trustKey:"3255554",xpid:"VwQCVFNWDBAFUlVTDwMOVlE=",licenseKey:"NRJS-49d1957d7e9674a128f",applicationID:"564182905",browserID:"1834328805"};;/*! For license information please see nr-loader-spa-1.324.0.min.js.LICENSE.txt */

## Resultados

In [8]:
results = soup.find_all('li', {'class':'serp-snippet ad featured'})

In [9]:
# length
len(results)

29

In [10]:
results[1]

<li class="serp-snippet ad featured" data-ev="30316130633534352d373232652d376432302d626362322d6134306132613334393935652d302d312d32" id="01a0c545-722e-7d20-bcb2-a40a2a34995e" itemscope="" itemtype="https://schema.org/Residence">
<div class="ad-ph"> <div class="agencyLogo" itemscope="" itemtype="https://schema.org/RealEstateAgent">
<img alt="GO Grupo Olavarria Bienes Raices" itemprop="logo" src="https://images.proppit.com/publisher/00b652ec-0157-4851-88d1-4557a6b448ea/logo.jpeg"/>
<meta content="GO Grupo Olavarria Bienes Raices" itemprop="name"/>
<meta content="https://images.proppit.com/publisher/00b652ec-0157-4851-88d1-4557a6b448ea/logo.jpeg" itemprop="image"/>
</div>
<div class="slider-ad">
<img alt="Departamento en  San Martin De Porres, Lima" src="https://img.resemmedia.com/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJpbmdlc3Rlci8wMWEwYzU0NS03MjJlLTdkMjAtYmNiMi1hNDBhMmEzNDk5NWUvMjJlZTE1MTU0MmE1MzZjZGI3MGI3ZjU4ZDhhNTdjNzFhOTM2MmIxOWQzNGU5ZTA3YTBkMDNiN2E0NmNjMzYzZi5qcGVnIiwiYnJhbmQiOiJyZXNlbSIsImVkaXRzIjp7InJvdGF0ZSI6bnVsbCwicmVzaXplIjp7IndpZHRoIjozNTQsImhlaWdodCI6MjQwLCJmaXQiOiJjb3ZlciJ9fX0="/><img alt="Departamento en  San Martin De Porres, Lima" data-lazy="https://img.resemmedia.com/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJpbmdlc3Rlci8wMWEwYzU0NS03MjJlLTdkMjAtYmNiMi1hNDBhMmEzNDk5NWUvYjBlNTRiOTc4ZjgyOTVlZWNlOGQ0ODEyOTBkMDQ5YTlhYjRiMTBmNzMyMDAzZmM0OGYyZjA5ZmE5MjVkNTY5NS5qcGVnIiwiYnJhbmQiOiJyZXNlbSIsImVkaXRzIjp7InJvdGF0ZSI6bnVsbCwicmVzaXplIjp7IndpZHRoIjozNTQsImhlaWdodCI6MjQwLCJmaXQiOiJjb3ZlciJ9fX0=" src="https://script.resemmedia.com/images/images/loading-image-6.svg"/><img alt="Departamento en  San Martin De Porres, Lima" data-lazy="https://img.resemmedia.com/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJpbmdlc3Rlci8wMWEwYzU0NS03MjJlLTdkMjAtYmNiMi1hNDBhMmEzNDk5NWUvNjgxOTIyYTE2OTYyOTU2ZWY2NDdmMTAwMTFlNjM0NGYwYWJmN2ZiMDkwNWJhMmJmZDkxMDQwNzc5MjdjMDE5ZS5qcGVnIiwiYnJhbmQiOiJyZXNlbSIsImVkaXRzIjp7InJvdGF0ZSI6bnVsbCwicmVzaXplIjp7IndpZHRoIjozNTQsImhlaWdodCI6MjQwLCJmaXQiOiJjb3ZlciJ9fX0=" src="https://script.resemmedia.com/images/images/loading-image-6.svg"/><img alt="Departamento en  San Martin De Porres, Lima" data-lazy="https://img.resemmedia.com/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJpbmdlc3Rlci8wMWEwYzU0NS03MjJlLTdkMjAtYmNiMi1hNDBhMmEzNDk5NWUvNDYxZTdmYmQ5YmNiMjEwNjNkNjYxNjk0ZmZjNTY1NDQwOWE2NGUxMzk3NmRjY2ZjNTMyODE0NzFhNmJkOTAzMi5qcGVnIiwiYnJhbmQiOiJyZXNlbSIsImVkaXRzIjp7InJvdGF0ZSI6bnVsbCwicmVzaXplIjp7IndpZHRoIjozNTQsImhlaWdodCI6MjQwLCJmaXQiOiJjb3ZlciJ9fX0=" src="https://script.resemmedia.com/images/images/loading-image-6.svg"/><img alt="Departamento en  San Martin De Porres, Lima" data-lazy="https://img.resemmedia.com/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJpbmdlc3Rlci8wMWEwYzU0NS03MjJlLTdkMjAtYmNiMi1hNDBhMmEzNDk5NWUvNTdkNGE0NDAzNDY2OWM0MGRlODk0NGMwYzAzODhlZDE5ODUyY2UzMDZhYzFmZDE1NjM0YzQ4NmJjOGExNjUyMy5qcGVnIiwiYnJhbmQiOiJyZXNlbSIsImVkaXRzIjp7InJvdGF0ZSI6bnVsbCwicmVzaXplIjp7IndpZHRoIjozNTQsImhlaWdodCI6MjQwLCJmaXQiOiJjb3ZlciJ9fX0=" src="https://script.resemmedia.com/images/images/loading-image-6.svg"/><img alt="Departamento en  San Martin De Porres, Lima" data-lazy="https://img.resemmedia.com/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJpbmdlc3Rlci8wMWEwYzU0NS03MjJlLTdkMjAtYmNiMi1hNDBhMmEzNDk5NWUvNWRhZGQ0ZTA5NzJlYzNiZGNjYzg3MmJjZTI5YjUzZmU5NDRiMWE5NjNjNDE3Y2E3NmEyNWJjODUyYmNiMDNhNC5qcGVnIiwiYnJhbmQiOiJyZXNlbSIsImVkaXRzIjp7InJvdGF0ZSI6bnVsbCwicmVzaXplIjp7IndpZHRoIjozNTQsImhlaWdodCI6MjQwLCJmaXQiOiJjb3ZlciJ9fX0=" src="https://script.resemmedia.com/images/images/loading-image-6.svg"/><img alt="Departamento en  San Martin De Porres, Lima" data-lazy="https://img.resemmedia.com/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJpbmdlc3Rlci8wMWEwYzU0NS03MjJlLTdkMjAtYmNiMi1hNDBhMmEzNDk5NWUvNzI4NGMwNDMyMWVmYjFlNjJjZWM4NjhhMTBlZWM2YTE1Mjc1N2IzZjJjZWIzNzA4ZTk3NjA0NGUwMTVkOTE4NC5qcGVnIiwiYnJhbmQiOiJyZXNlbSIsImVkaXRzIjp7InJvdGF0ZSI6bnVsbCwicmVzaXplIjp7IndpZHRoIjozNTQsImhlaWdodCI6MjQwLCJmaXQiOiJjb3ZlciJ9fX0=" src="https://script.resemmedia.com/images/images/loading-image-6.svg"/><img alt="Departamento en  San Martin De Porres, Lima" data-lazy="https://img.resemmedia.com/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJpbmdlc3Rlci8wMWEwYzU0NS03MjJlLTdkMjAtYmNiMi1hNDBhMmEzNDk5NWUvMTA3NDM3Mzg5M2VlMzBkOWJjZjFlMzIzOGEwNDUyNzFkZGZiM2QzNmMyZGYzMjAyZDEwOTYxMjU3MWRlNGNlNC5qcGVnIiwiYnJhbmQiOiJyZXNlbSIsImVkaXRzIjp7InJvdGF0ZSI6bnVsbCwicmVzaXplIjp7IndpZHRoIjozNTQsImhlaWdodCI6MjQwLCJmaXQiOiJjb3ZlciJ9fX0=" src="https://script.resemmedia.com/images/images/loading-image-6.svg"/><img alt="Departamento en  San Martin De Porres, Lima" data-lazy="https://img.resemmedia.com/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJpbmdlc3Rlci8wMWEwYzU0NS03MjJlLTdkMjAtYmNiMi1hNDBhMmEzNDk5NWUvOTdiYWMwZjBjYzE4NDEyNTA5MTE5YzIwNDhjZjgxYTBhOTIyOTY3MTBlZDNiYmUwYjQ4MTc2NjU0YzdjMjk3ZC5qcGVnIiwiYnJhbmQiOiJyZXNlbSIsImVkaXRzIjp7InJvdGF0ZSI6bnVsbCwicmVzaXplIjp7IndpZHRoIjozNTQsImhlaWdodCI6MjQwLCJmaXQiOiJjb3ZlciJ9fX0=" src="https://script.resemmedia.com/images/images/loading-image-6.svg"/><img alt="Departamento en  San Martin De Porres, Lima" data-lazy="https://img.resemmedia.com/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJpbmdlc3Rlci8wMWEwYzU0NS03MjJlLTdkMjAtYmNiMi1hNDBhMmEzNDk5NWUvOGQ3N2MzM2Q3MDk4MjFhMGEzNmQ2MjZlOTE5ZTZjMjhiZjdkYWZiNzVhNmVhN2Y0NDY0ZGQ3MTk0ZDMyNWI2Yi5qcGVnIiwiYnJhbmQiOiJyZXNlbSIsImVkaXRzIjp7InJvdGF0ZSI6bnVsbCwicmVzaXplIjp7IndpZHRoIjozNTQsImhlaWdodCI6MjQwLCJmaXQiOiJjb3ZlciJ9fX0=" src="https://script.resemmedia.com/images/images/loading-image-6.svg"/><img alt="Departamento en  San Martin De Porres, Lima" data-lazy="https://img.resemmedia.com/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJpbmdlc3Rlci8wMWEwYzU0NS03MjJlLTdkMjAtYmNiMi1hNDBhMmEzNDk5NWUvYTM4ZjJhZTc2ZWZhNWY1NzY0ZTllNTU4N2M4MjlkNTViNzMyYmYyMGVjODkzMDNlY2IxNGQyNDBkOWM5NDMyZC5qcGVnIiwiYnJhbmQiOiJyZXNlbSIsImVkaXRzIjp7InJvdGF0ZSI6bnVsbCwicmVzaXplIjp7IndpZHRoIjozNTQsImhlaWdodCI6MjQwLCJmaXQiOiJjb3ZlciJ9fX0=" src="https://script.resemmedia.com/images/images/loading-image-6.svg"/><img alt="Departamento en  San Martin De Porres, Lima" data-lazy="https://img.resemmedia.com/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJpbmdlc3Rlci8wMWEwYzU0NS03MjJlLTdkMjAtYmNiMi1hNDBhMmEzNDk5NWUvOGVlN2QxNmNkZWYzOGNhMjFjYzQ3YmQxNjczNjcxMjNjODM4ZTU5OTBiMTI4YjYxYzQ0NWZkYTliNjVhZTI5ZS5qcGVnIiwiYnJhbmQiOiJyZXNlbSIsImVkaXRzIjp7InJvdGF0ZSI6bnVsbCwicmVzaXplIjp7IndpZHRoIjozNTQsImhlaWdodCI6MjQwLCJmaXQiOiJjb3ZlciJ9fX0=" src="https://script.resemmedia.com/images/images/loading-image-6.svg"/><img alt="Departamento en  San Martin De Porres, Lima" data-lazy="https://img.resemmedia.com/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJpbmdlc3Rlci8wMWEwYzU0NS03MjJlLTdkMjAtYmNiMi1hNDBhMmEzNDk5NWUvOGFiNTQ0ODM3YTg2NThmYmIwZGQ5ZDBiY2Q3NTg4YTljNjMzZGUxYTk4NTdmY2ZlMGM3ZTc0MDhlNGI0NzY4NC5qcGVnIiwiYnJhbmQiOiJyZXNlbSIsImVkaXRzIjp7InJvdGF0ZSI6bnVsbCwicmVzaXplIjp7IndpZHRoIjozNTQsImhlaWdodCI6MjQwLCJmaXQiOiJjb3ZlciJ9fX0=" src="https://script.resemmedia.com/images/images/loading-image-6.svg"/><img alt="Departamento en  San Martin De Porres, Lima" data-lazy="https://img.resemmedia.com/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJpbmdlc3Rlci8wMWEwYzU0NS03MjJlLTdkMjAtYmNiMi1hNDBhMmEzNDk5NWUvNWMzYWE1Y2M3MGJlZDVlNTFkZjAzZWYxNjFiZDkxZTI2NTY1ZjIzYjFhNjBmMGU4YzBiYTc3NzUwNTMwODZiNi5qcGVnIiwiYnJhbmQiOiJyZXNlbSIsImVkaXRzIjp7InJvdGF0ZSI6bnVsbCwicmVzaXplIjp7IndpZHRoIjozNTQsImhlaWdodCI6MjQwLCJmaXQiOiJjb3ZlciJ9fX0=" src="https://script.resemmedia.com/images/images/loading-image-6.svg"/><img alt="Departamento en  San Martin De Porres, Lima" data-lazy="https://img.resemmedia.com/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJpbmdlc3Rlci8wMWEwYzU0NS03MjJlLTdkMjAtYmNiMi1hNDBhMmEzNDk5NWUvZjYxNzRiN2JhNmVhMzJiZGVmZDY5MjcxYWMzMzQwYjZjYzZlYmFjZDNiOTVhZmZiYTgyMWU4MWIyMWM5ZTZlMS5qcGVnIiwiYnJhbmQiOiJyZXNlbSIsImVkaXRzIjp7InJvdGF0ZSI6bnVsbCwicmVzaXplIjp7IndpZHRoIjozNTQsImhlaWdodCI6MjQwLCJmaXQiOiJjb3ZlciJ9fX0=" src="https://script.resemmedia.com/images/images/loading-image-6.svg"/><img alt="Departamento en  San Martin De Porres, Lima" data-lazy="https://img.resemmedia.com/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJpbmdlc3Rlci8wMWEwYzU0NS03MjJlLTdkMjAtYmNiMi1hNDBhMmEzNDk5NWUvZTRkZjQ3MGVjYjM1MDJjYmFlZGVmMDNlNjFhYjIyYjM3ODQyZjVkNDRhZTRhY2E1M2FkOWVhMGEzMzJlZjE5Ny5qcGVnIiwiYnJhbmQiOiJyZXNlbSIsImVkaXRzIjp7InJvdGF0ZSI6bnVsbCwicmVzaXplIjp7IndpZHRoIjozNTQsImhlaWdodCI6MjQwLCJmaXQiOiJjb3ZlciJ9fX0=" src="https://script.resemmedia.com/images/images/loading-image-6.svg"/><img alt="Departamento en  San Martin De Porres, Lima" data-lazy="https://img.resemmedia.com/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJpbmdlc3Rlci8wMWEwYzU0NS03MjJlLTdkMjAtYmNiMi1hNDBhMmEzNDk5NWUvOWRkZGQ0NWMwZDBiNzAzOWU1NjE1NjkyYjBjODQxYTBiMGNkNzVmZjJmNjkwODdiNDc0YmM3ZDE4ZTQ2OTE3Zi5qcGVnIiwiYnJhbmQiOiJyZXNlbSIsImVkaXRzIjp7InJvdGF0ZSI6bnVsbCwicmVzaXplIjp7IndpZHRoIjozNTQsImhlaWdodCI6MjQwLCJmaXQiOiJjb3ZlciJ9fX0=" src="https://script.resemmedia.com/images/images/loading-image-6.svg"/><img alt="Departamento en  San Martin De Porres, Lima" data-lazy="https://img.resemmedia.com/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJpbmdlc3Rlci8wMWEwYzU0NS03MjJlLTdkMjAtYmNiMi1hNDBhMmEzNDk5NWUvY2U0YTAxYzU1NTc2YzYwYThmYTFlZDljNmIzYTdkYWMwNGI0YWE2ZGFjMGQ4Nzc4OGEzYjNiOTkzMzU4YzNmZC5qcGVnIiwiYnJhbmQiOiJyZXNlbSIsImVkaXRzIjp7InJvdGF0ZSI6bnVsbCwicmVzaXplIjp7IndpZHRoIjozNTQsImhlaWdodCI6MjQwLCJmaXQiOiJjb3ZlciJ9fX0=" src="https://script.resemmedia.com/images/images/loading-image-6.svg"/>
<div class="slider-cta" style="background-image: url(https://img.resemmedia.com/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJpbmdlc3Rlci8wMWEwYzU0NS03MjJlLTdkMjAtYmNiMi1hNDBhMmEzNDk5NWUvMjJlZTE1MTU0MmE1MzZjZGI3MGI3ZjU4ZDhhNTdjNzFhOTM2MmIxOWQzNGU5ZTA3YTBkMDNiN2E0NmNjMzYzZi5qcGVnIiwiYnJhbmQiOiJyZXNlbSIsImVkaXRzIjp7InJvdGF0ZSI6bnVsbCwicmVzaXplIjp7IndpZHRoIjozNTQsImhlaWdodCI6MjQwLCJmaXQiOiJjb3ZlciJ9fX0=)">
<div class="slider-cta-overlay-back"></div>
<p>¿Te gusta?</p><button class="slider-main-cta btn-contact" data-adid="01a0c545-722e-7d20-bcb2-a40a2a34995e" data-contactsubtype="ADS_LISTING_CAROUSEL" data-where="listing-carousel">Contactar</button><button class="slider-secondary-cta" data-type="carousel">Ver en detalle</button>
</div>
</div><section itemprop="photo" itemscope="" itemtype="https://schema.org/CreativeWork"><meta content="https://img.resemmedia.com/eyJidWNrZXQiOiJwcmQtbGlmdWxsY29ubmVjdC1iYWNrZW5kLWIyYi1pbWFnZXMiLCJrZXkiOiJpbmdlc3Rlci8wMWEwYzU0NS03MjJlLTdkMjAtYmNiMi1hNDBhMmEzNDk5NWUvMjJlZTE1MTU0MmE1MzZjZGI3MGI3ZjU4ZDhhNTdjNzFhOTM2MmIxOWQzNGU5ZTA3YTBkMDNiN2E0NmNjMzYzZi5qcGVnIiwiYnJhbmQiOiJyZXNlbSIsImVkaXRzIjp7InJvdGF0ZSI6bnVsbCwicmVzaXplIjp7IndpZHRoIjozNTQsImhlaWdodCI6MjQwLCJmaXQiOiJjb3ZlciJ9fX0=" itemprop="url"/></section>
<span class="slider-chevron left"></span><span class="slider-chevron right"></span>
<div class="icons"> <span class="icon photo" data-total="18"><span class="current">1</span>/<span class="total">18</span></span> <span class="icon video"></span> </div>
</div>
<div class="ad-data">
<div class="data">
<div class="price">				$ 377.94

                    <div class="top-label">destacado</div>
</div>
<h2 class="title" itemprop="name"><a class="detail-redirection" href="/inmueble/72b4-bd38-1a0c5cb-a40a2a3499e4-7da6" itemprop="url">Departamento en  San Martin De Porres, Lima</a></h2>
<p class="description" itemprop="description">¡DEPARTAMENTO EN ESTRENO! Cómodo, Equipado y con Cochera – Condominio Las AcaciasPrecio: S/ 1,300 Soles (Mantenimiento y ...</p>
<div class="adCharacteristics">
<span class="numbers"> <span class="areaBuilt">63.1m2</span> <span class="rooms">3<i class="icon-r-bed"></i></span> <span class="bathrooms">2<i class="icon-r-bathroom"></i></span> </span>
</div>
</div>
<div class="actions">
<span class="like heart-login" data-adid="01a0c545-722e-7d20-bcb2-a40a2a34995e" data-text="Favorito"></span>
<div class="buttons"> <button class="btn-phone" data-adid="01a0c545-722e-7d20-bcb2-a40a2a34995e" data-partner="GO Grupo Olavarria Bienes Raices" data-where="listing">Llamar</button>
<button class="btn-contact" data-adid="01a0c545-722e-7d20-bcb2-a40a2a34995e" data-where="listing">Contactar</button>
</div>
</div>
</div>
<span itemprop="address" itemscope="" itemtype="https://schema.org/PostalAddress"><meta content="PE" itemprop="addressCountry"/><meta content="San Martin de Porres, Lima" itemprop="addressLocality"/><meta content="Lima Departamento" itemprop="addressRegion"/><meta content="" itemprop="streetAddress"/></span>
<span itemprop="geo" itemscope="" itemtype="https://schema.org/GeoCoordinates"><meta content="-11.936979" itemprop="latitude"/><meta content="-77.041483" itemprop="longitude"/></span>
</li>

## objetivos: Datos Necesarios

In [11]:
# Name
# Price
# Area
# Rooms
# Bathrooms
# Descryption
# Url

### Nombre
- a porque el nombre esta dentro de un ancla (link): <a
- strip=True --> limpia espacios

In [12]:
results[0].find('a', {'class': 'detail-redirection'}).get_text(strip=True)

'Departamento en  Calle Clemente Palma, Lima, Perú'

### Precio
- div porque el precio esta dentro de una division: <div

In [13]:
results[0].find('div', {'class':'price'}).get_text(strip=True)

'$ 1,200destacado'

### Área
- span porque el metraje esta dentro de una linea corta: <spa

In [14]:
results[0].find('span', {'class':'areaBuilt'}).get_text(strip=True)

'120m2'

### Habitaciones

In [15]:
results[0].find('span', {'class':'rooms'}).get_text(strip=True)

'3'

### Baños

In [16]:
results[0].find('span', {'class':'bathrooms'}).get_text(strip=True)

'2'

### Descripción

In [17]:
results[0].find('p', {'class':'description'}).get_text(strip=True)

'ALQUILO FLAT EN 4TO PISO CON ASCENSOR EN CALLE CLEMENTE - MAGDALENA\nAT: 120 M2 , SE ALQUILA: US$1200 DOLARES\nSALA COMEDOR...'

### URL Relativa

In [18]:
relative_url = results[0].find('a', {'class': 'detail-redirection'}).get('href')

In [19]:
relative_url

'/inmueble/9f5e-b3f4-1a0a6a2-4e50f7399bd8-7626'

In [20]:
root_url = 'https://www.laencontre.com.pe'

In [21]:
# combine URLs
url_combined = root_url + relative_url

In [22]:
url_combined

'https://www.laencontre.com.pe/inmueble/9f5e-b3f4-1a0a6a2-4e50f7399bd8-7626'

## Unir todo dentro de un bucle For (Paginación)

In [23]:
product_name = []
product_price = []
product_area = []
product_rooms = []
product_bathrooms = []
product_description = []
relative_url = []


for result in results:
    
    # name
    try:
        product_name.append(result.find('a', {'class': 'detail-redirection'}).get_text(strip=True)) 
    except:
        product_name.append('n/a') # <--. Si la etiqueta no existe o falla, atrapa el error y agrega 'n/a', luego continua agregando

    # price
    try:
        product_price.append(result.find('div', {'class':'price'}).get_text(strip=True)) 
    except:
        product_price.append('n/a')

    # area
    try:
        product_area.append(result.find('span', {'class':'areaBuilt'}).get_text(strip=True)) 
    except:
        product_area.append('n/a')

    # rooms
    try:
        product_rooms.append(result.find('span', {'class':'rooms'}).get_text(strip=True)) 
    except:
        product_rooms.append('n/a')
        
    # bathrooms
    try:
        product_bathrooms.append(result.find('span', {'class':'bathrooms'}).get_text(strip=True))
    except:
        product_bathrooms.append('n/a')

    #description
    try:
        product_description.append(result.find('p', {'class':'description'}).get_text(strip=True))
    except:
        product_description.append('n/a')


    # relative URL
    try:
        relative_url.append(result.find('a', {'class': 'detail-redirection'}).get('href'))
    except:
        relative_url.append('n/a')

### Combinar URLs
- urllib.parse : reconstruye

In [24]:
url_combined = []

for link in relative_url:
    url_combined.append(urllib.parse.urljoin(root_url, link))

## Crear DataFrame de Pandas

In [25]:
product_overview = pd.DataFrame({'Name': product_name, 'Price':product_price, 'Area (m2)':product_area,
                                'Rooms': product_rooms, 'Bathrooms': product_bathrooms, 'Description':product_description,
                                'Link': url_combined})

In [26]:
product_overview.head()

,Name,Price,Area (m2),Rooms,Bathrooms,Description,Link
0,"Departamento en Calle Clemente Palma, Lima, Perú","$ 1,200destacado",120m2,3,2,ALQUILO FLAT EN 4TO PISO CON ASCENSOR EN CALLE...,https://www.laencontre.com.pe/inmueble/9f5e-b3...
1,"Departamento en San Martin De Porres, Lima",$ 377.94destacado,63.1m2,3,2,"¡DEPARTAMENTO EN ESTRENO! Cómodo, Equipado y c...",https://www.laencontre.com.pe/inmueble/72b4-bd...
2,"Departamento en San Martín De Porres, Lima, L...",$ 261.65,58m2,2,1,Imagina vivir en un lugar donde todo te queda ...,https://www.laencontre.com.pe/inmueble/e7dd-a8...
3,"Departamento en San Martin De Porres, Lima",$ 261.65destacado,63m2,2,1,ALQUILO DEPARTAMENTO EN AV. EL AMARGON LOS OLI...,https://www.laencontre.com.pe/inmueble/2072-a9...
4,"Departamento en San Martin De Porres, Lima",$ 206,75m2,1,1,"Acogedor y funcional departamento de 75 m², ub...",https://www.laencontre.com.pe/inmueble/8d67-9f...

## Descarga

In [27]:
product_overview.to_csv('Apartments.csv', index=False)

## Parte 2 - Paginación - Extraer 20 Páginas

In [28]:
product_name = []
product_price = []
product_area = []
product_rooms = []
product_bathrooms = []
product_description = []
relative_url = []

for i in range (1,40):
    
    # website in variable
    if i == 1:
        website = 'https://www.laencontre.com.pe/alquiler/departamentos/lima/san-martin-porres'
    else:
        website = f'https://www.laencontre.com.pe/alquiler/departamentos/lima/san-martin-porres/p_{i}'
    
    # request
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'}
    response = requests.get(website, headers=headers)
    
    # soup object
    soup = BeautifulSoup(response.content, 'html.parser')
   
    # results
    results = soup.find_all('li', {'class':'serp-snippet ad featured'})
    
    # loop through results
    for result in results:
    
        # name
        try:
            product_name.append(result.find('a', {'class': 'detail-redirection'}).get_text(strip=True)) 
        except:
            product_name.append('n/a') # <--. Si la etiqueta no existe o falla, atrapa el error y agrega 'n/a', luego continua agregando

        # price
        try:
            product_price.append(result.find('div', {'class':'price'}).get_text(strip=True)) 
        except:
            product_price.append('n/a')

        # area
        try:
            product_area.append(result.find('span', {'class':'areaBuilt'}).get_text(strip=True)) 
        except:
            product_area.append('n/a')

        # rooms
        try:
            product_rooms.append(result.find('span', {'class':'rooms'}).get_text(strip=True)) 
        except:
            product_rooms.append('n/a')
            
        # bathrooms
        try:
            product_bathrooms.append(result.find('span', {'class':'bathrooms'}).get_text(strip=True))
        except:
            product_bathrooms.append('n/a')

        #description
        try:
            product_description.append(result.find('p', {'class':'description'}).get_text(strip=True))
        except:
            product_description.append('n/a')


        # relative URL
        try:
            relative_url.append(result.find('a', {'class': 'detail-redirection'}).get('href'))
        except:
            relative_url.append('n/a')

In [29]:
url_combined = []

for link in relative_url:
    url_combined.append(urllib.parse.urljoin(root_url, link))

In [30]:
product_overview = pd.DataFrame({'Name': product_name, 'Price':product_price, 'Area (m2)':product_area,
                                'Rooms': product_rooms, 'Bathrooms': product_bathrooms, 'Description':product_description,
                                'Link': url_combined})

In [31]:
product_overview

,Name,Price,Area (m2),Rooms,Bathrooms,Description,Link
0,"Departamento en Calle Clemente Palma, Lima, Perú","$ 1,200destacado",120m2,3,2,ALQUILO FLAT EN 4TO PISO CON ASCENSOR EN CALLE...,https://www.laencontre.com.pe/inmueble/9f5e-b3...
1,"Departamento en San Martin De Porres, Lima",$ 377.94destacado,63.1m2,3,2,"¡DEPARTAMENTO EN ESTRENO! Cómodo, Equipado y c...",https://www.laencontre.com.pe/inmueble/72b4-bd...
2,"Departamento en San Martín De Porres, Lima, L...",$ 261.65,58m2,2,1,Imagina vivir en un lugar donde todo te queda ...,https://www.laencontre.com.pe/inmueble/e7dd-a8...
3,"Departamento en San Martin De Porres, Lima",$ 261.65destacado,63m2,2,1,ALQUILO DEPARTAMENTO EN AV. EL AMARGON LOS OLI...,https://www.laencontre.com.pe/inmueble/2072-a9...
4,"Departamento en San Martin De Porres, Lima",$ 206,75m2,1,1,"Acogedor y funcional departamento de 75 m², ub...",https://www.laencontre.com.pe/inmueble/8d67-9f...
5,"Departamento en San Martin De Porres, Lima",$ 206,75m2,1,1,"Acogedor y funcional departamento de 75 m², ub...",https://www.laencontre.com.pe/inmueble/9706-99...
6,Departamento en Avenida Antúnez De Mayolo 150...,$ 377.94destacado,65m2,2,1,Departamento de 2 Dormitorios en Alquiler – Lo...,https://www.laencontre.com.pe/inmueble/9718-83...
7,Departamento en Avenida Antúnez De Mayolo 150...,$ 348.86destacado,60m2,2,1,Departamento de 2 Dormitorios en Alquiler – Lo...,https://www.laencontre.com.pe/inmueble/a72d-8c...
8,"Departamento en Calle Veintiocho, San Martín ...",$ 290.72destacado,95m2,2,1,ALQUILO DEPARTAMENTO FRENTE A PARQUE EN SAN MA...,https://www.laencontre.com.pe/inmueble/669b-9b...
9,Departamento en Avenida Almirante Miguel Grau...,$ 334.33,60m2,2,1,¿Imaginas despertar cada mañana con luz natura...,https://www.laencontre.com.pe/inmueble/e247-8f...
10,"Departamento en Avenida 12 De Octubre, San Ma...",$ 290.72,70m2,2,1,🌷Se alquila hermoso departamento de estreno en...,https://www.laencontre.com.pe/inmueble/3b99-ad...
11,"Departamento en Calle 13, San Martín De Porre...",$ 407.01,82.17m2,3,2,​🏡✨ ¡Alquila este acogedor dúplex en Condomini...,https://www.laencontre.com.pe/inmueble/c7a1-a0...
12,"Departamento en Pasaje A, San Martín De Porre...",$ 407.01,140m2,4,2,SE ALQUILA AMPLIO DEPARTAMENTO EN PISO 2 - UR...,https://www.laencontre.com.pe/inmueble/5762-ad...
13,"Departamento en Jirón Arco Iris, Cooperativa ...",$ 232.58,50m2,1,1,🏡 MINIDEPARTAMENTO EN ALQUILER | SAN MARTÍN DE...,https://www.laencontre.com.pe/inmueble/84b2-b4...
14,"Departamento en San Martin De Porres, Lima",$ 290.72,120m2,3,1,DEPARTAMENTO EN ALQUILER - PRIMER PISO – SAN M...,https://www.laencontre.com.pe/inmueble/4d50-84...
15,"Departamento en San Martín De Porres, Lima, L...",$ 343.05,110m2,3,2,Departamento de 100 m2 en alquiler a minutos d...,https://www.laencontre.com.pe/inmueble/321f-bf...
16,"Departamento en San Martín De Porres, Lima, L...","$ 1,180",110m2,3,3,✅Buscas alquilar un departamento en SMP y que ...,https://www.laencontre.com.pe/inmueble/6bd8-a6...
17,"Departamento en San Martin De Porres, Lima",$ 348.86,80m2,2,1,ALQUILO DEPARTAMENTO DE 80 M2EN SAN MARTIN DE ...,https://www.laencontre.com.pe/inmueble/7dc8-b6...
18,"Departamento en San Martin De Porres, Lima",$ 337,126m2,3,1,Alquilo departamento frente a parque con ilumi...,https://www.laencontre.com.pe/inmueble/f423-86...
19,"Departamento en San Martin De Porres, Lima",$ 412,109.69m2,3,1,Ubicado entre Av. Quilca y Av. Perú\nVive en u...,https://www.laencontre.com.pe/inmueble/95f4-92...
20,"Departamento en San Martín De Porres 15109, S...",$ 436.08destacado,70m2,2,1,"📍 Ubicación privilegiada: Frente a parque, en ...",https://www.laencontre.com.pe/inmueble/ebca-a5...
21,"Departamento en San Martin De Porres, Lima",$ 232.58,46m2,2,1,ALQUILO DEPARTAMENTO DE 46 M2 EN SAN MARTIN DE...,https://www.laencontre.com.pe/inmueble/a6be-a8...
22,"Departamento en Urb. Ingeniería, San Martín D...",$ 610.51destacado,77m2,2,n/a,🏢 Departamento de Estreno 77 m² en Alquiler\nI...,https://www.laencontre.com.pe/inmueble/e1dd-99...
23,"Departamento en San Martin De Porres, Lima",$ 203.5,33m2,1,1,ALQUILO MINIDEPARTAMENTO DE 33 M2 EN SAN MARTI...,https://www.laencontre.com.pe/inmueble/ba60-a6...
24,"Departamento en San Martin De Porres, Lima",$ 203.5,33m2,1,1,ALQUILO MINIDEPARTAMENTO DE 33 M2 EN SAN MARTI...,https://www.laencontre.com.pe/inmueble/affd-91...
25,"Departamento en Avenida San Diego De Alcala, ...",$ 319.79destacado,120m2,3,2,✨ ¡Oportunidad en San Martín de Porres! Depart...,https://www.laencontre.com.pe/inmueble/af19-c0...
26,"Departamento en Avenida Pacasmayo, Urbanizaci...",$ 261.65destacado,75m2,3,1,Alquiler de un moderno departamento de estreno...,https://www.laencontre.com.pe/inmueble/ca9e-83...
27,"Departamento en Av. Pacasmayo 22, San Martín ...",$ 290.72destacado,75m2,3,1,ALQUILER DE DEPARTAMENTO EN SAN MARTIN DE PORR...,https://www.laencontre.com.pe/inmueble/6144-a2...
28,"Departamento en San Martin De Porres, Lima",$ 232.58,46m2,n/a,n/a,ALQUILO DEPARTAMENTO DE 46 M2 EN SAN MARTIN DE...,https://www.laencontre.com.pe/inmueble/9fc0-92...
29,"Departamento en Jirón Maracaibo, Perú 1ra Zon...",$ 377.94,90.68m2,3,2,✨ ¡ALQUILA TU NUEVO HOGAR DE ESTRENO EN SMP! ✨...,https://www.laencontre.com.pe/inmueble/1b10-bf...
30,"Departamento en Jirón Maracaibo, Perú 1ra Zon...",$ 261.65,59.76m2,2,2,🏡✨ ¡ALQUILA TU NUEVO HOGAR DE ESTRENO EN SMP! ...,https://www.laencontre.com.pe/inmueble/ac79-b6...
31,"Departamento en San Martin De Porres, Lima",$ 593,117m2,n/a,3,ALQUILER DE 2 DEPARTAMENTOS PARA OFICINA – AV....,https://www.laencontre.com.pe/inmueble/eb9-85f...
32,"Departamento en San Martin De Porres, Lima",$ 340,65m2,2,1,CONTACTO AMY URRIETA 9*3*8*9*2*2*3*3*0*\nSe al...,https://www.laencontre.com.pe/inmueble/8c41-bf...
33,"Departamento en San Martin De Porres, Lima",$ 440,80m2,1,1,ALQUILER DE DEPARTAMENTO EN SAN MARTIN DE PORR...,https://www.laencontre.com.pe/inmueble/a857-b3...
34,"Departamento en San Martin De Porres, Lima",$ 350,60m2,2,1,CONTACTO: AMY URRIETA 9*3*8*9*2*2*3*3*0\nSe al...,https://www.laencontre.com.pe/inmueble/9afd-b5...
35,"Departamento en San Martin De Porres, Lima",$ 593,117m2,n/a,3,ALQUILER DE 2 DEPARTAMENTOS PARA OFICINA – AV....,https://www.laencontre.com.pe/inmueble/789-9d9...
36,"Departamento en Calle Sta. Monica 190, San Ma...",$ 232.58,60m2,2,2,🏡 ¡ALQUILA TU NUEVO DEPARTAMENTO! ✨\n\n📍 Depar...,https://www.laencontre.com.pe/inmueble/b193-ad...
37,"Departamento en Jr Bello Horizonte 2559, Jr, ...",$ 290.72,80m2,2,2,Para mas información: Victoria Quispe 9.2.2.5....,https://www.laencontre.com.pe/inmueble/3a60-83...
38,"Departamento en San Martin De Porres, Lima",$ 343,113m2,5,2,¡Vive frente al parque en San Martín de Porres...,https://www.laencontre.com.pe/inmueble/c95b-b5...
39,"Departamento en C. Mayor Jose Andres Razuri, ...",$ 174.43,36m2,1,1,✨ ¡Descubre tu próximo hogar en San Martín de ...,https://www.laencontre.com.pe/inmueble/a1a2-9b...
40,"Departamento en Calle Los Ficus Mz.h - Lt.12,...",$ 436.08,125m2,3,1,Mas información:\nJuana Panduro 9.9.2.8 1.5...,https://www.laencontre.com.pe/inmueble/11eb-aa...
41,Departamento en Av. El Sol De Naranjal Mz.d -...,$ 159.9,50m2,3,1,🏡 ¡ALQUILO DEPARTAMENTO EN 4.º PISO – EXCELENT...,https://www.laencontre.com.pe/inmueble/9ee1-9b...

In [32]:
product_overview['Price'] = (product_overview['Price'].str.split('destacado').str[0].str.strip())
product_overview['Area (m2)'] = (product_overview['Area (m2)'].str.split('m2').str[0].str.strip())

## Descarga

In [33]:
product_overview.to_csv('multiple-apartments-pages.csv', index=False)